# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Project

on:
  push:
    branches: ["main"]
    paths: ["/"]
#   push:
#     branches: ["main"]
#     paths: ["order/**"]
#   pull_request:
#     branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#       - name: create docker network
#         run: docker network create store
#       - name: run make file
#         run: make run
#   test_order_service:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: set up golang
#         uses: actions/setup-go@v4
#         with:
#           go-version: 1.20
#       - name: make install-migration
#         run: make install-migration
#       - name: run test
#         run: yes| make test
#         working-directory: ./order

#     # - name: Set up Go
#     #   uses: actions/setup-go@v4
#     #   with:
#     #     go-version: '1.20'

#     # - name: Build
#     #   run: go build -v ./...

#     # - name: Test
#     #   run: go test -v ./...
